### ISSUE TITLE
[Jira] Component organizer menu options should contrast to darker, instead of lighter

### ISSUE THREAD

**Issue by brianwulbern** [lgdd/darth-ray#13]
When navigating to a [Component Organizer view](https://issues.liferay.com/projects/LRQA?selectedItem=net.brokenbuild.subcomponents:component-versions-organizer) the hover color on the left-hand menu is quite light.  I'd expect a shade darker to better channel the dark side of the theme. 🕶️ 

![component_version_organizer](https://user-images.githubusercontent.com/2567901/142416085-8eb38a76-e014-45e8-8886-e2ab9b0af272.png)

**Comment by lgdd** [comment]
@brianwulbern it should be fixed now with version 1.0.8+

**Comment by brianwulbern** [comment]
@lgdd looks great!
![fixed_component_view](https://user-images.githubusercontent.com/2567901/158123308-e3532ef1-9375-440a-9f75-8982655b3f95.gif)
