### ISSUE TITLE
[Jira] Links in pop-up dialogs don't display

### ISSUE THREAD

**Issue by brianwulbern** [lgdd/darth-ray#17]
When clicking the 'commits' link on a Jira ticket, the links within the popup dialog only display after hovering/highlighting those areas of the dialog.

![unique_commits_close_link_hidden](https://user-images.githubusercontent.com/2567901/163750023-9e36b269-84df-49b8-a721-3ae36f14ea9b.gif)

**Comment by brianwulbern** [comment]
This may be related to https://github.com/lgdd/darth-ray/issues/7

**Comment by lgdd** [comment]
Thanks @brianwulbern ! This should be fixed now with v1.0.9 :)

**Comment by brianwulbern** [comment]
w00t!

**Comment by brianwulbern** [comment]
Yep, it looks good!

![image](https://user-images.githubusercontent.com/2567901/164479667-e9c2947c-5ce7-4883-9d0b-68e6ad5ae266.png)
