### ISSUE TITLE
[Jira] Dark Backlog Support Needed

### ISSUE THREAD

**Issue by rbohl** [lgdd/darth-ray#8]
The backlog view of a kanban board is difficult to read. I'd try to fix it myself and send a PR but I am pretty lost with how to best add it. I'll mess with it a bit and see if I can discover anything worthwhile.

Thanks for the nice work on this!
![dark-backlog-views](https://user-images.githubusercontent.com/1728666/118851870-39dd1380-b8a0-11eb-9c20-dbbf2ee7ff1b.gif)

**Comment by lgdd** [comment]
Thanks for reporting this @rbohl. I added some colors similar to the kanban board.
Let me know in this issue if you spot anything wrong, I'm sure I missed some cases.

**Comment by rbohl** [comment]
Oh, that's _way_ better: thank you!
